apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: shop-policy
spec:
  l7Policies:
    waf: "/Common/asmpolicy_shop_f5lab_com"
  profiles:
    logProfiles:
      - /Common/Log illegal requests
  iRules:
    secure: "/Common/irule_not_found"
    priority: high